services:
  redis:
    image: redis
    profiles:
      - production
  
  frontend-build:
    container_name: bp-fe-build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./build:/src/build
    command: npx webpack --config /src/webpack.config.js
    profiles:
      - build

  server:
    container_name: bp-server
    build:
      context: ./BlissPortfolio
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./build:/app/build
      #- ${PORTFOLIO_DATA_SHARED_DIR}:/app/static/profile
    command: /start-server.sh
    profiles:
      - production

  frontend-dev:
      container_name: bliss-portfolio-frontend-dev
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      command: npm run start
      profiles:
        - development

  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
