name: Test and Deploy Bliss Portfolio # Replace with the name of your app

on:
  push:
    branches:
      - main  # replace with the branch you want to trigger the deployment

jobs:
  trigger_another_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Another Workflow
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/btschwartz12/deployers/actions/workflows/portfolio-deploy.yml/dispatches \
          -d '{"ref":"main","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'

