name: Generate a build and push to another branch

on:
  push:
    branches:
      - vps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          git clone -b vps git@github.com:btschwartz12/personal-website.git website-build
          cd website-build
          python3 -m venv env
          source env/bin/activate
          ./bin/install-noconfirm
          ./bin/build
          ./bin/serve
          cd ..
          rm -rf website-build
          echo Done
